Titel: Analysis I*
Vorlage: math

# November 22, 2012

Satz. a_n ≤ c_n ≤ b_n,  limn a_n = limn b_n = a. Dann ist (c_n) eine konvergente Folge
und limn c_n = a. 

Def. Eine *reelle* Folge (a_n)_{n in NN} heißt **monoton wachsend** falls gilt: a_{n+1} ≥ a_n für
alle n in NN, **monoton fallend**, falls a_{n+1} ≤ a_n für n in NN. Gilt sogar a_{n+1} > a_n 
 (a_{n+1} < a_n) für alle n in NN, dann heißt sie **streng monoton wachsend (fallend)**.

Satz. Eine *beschränkte*, monoton wachsende Folge ist konvergent.
Mit A=\{a_n : n in NN\} gilt: limn a_n = sup A. Ist (a_n) monoton fallend und beschränkt, so
gilt limn a_n = inf A. 

# November 22, 2012 (Übung)

Def. a in A sse RR heißt **Schranke** von A, wenn a untere oder obere Schranke von A ist. a heißt **optimale Schranke**, wenn a kleinste obere oder größte untere Schranke von A ist.
