Titel: hallo
Vorlage: math

# 20.11.2012

**Prop.** Seien ´a, b in ZZ, d = \text{ggT}(a, b)´. Dann gibt es ´x, y \in ZZ´, so dass ´d=xa+yb´.

**Bmk.** Der ´ggT(a, b´) ist die kleinste natürliche Zahl, die als lineare Kombination von a und b
darstellbar ist.

Lemma. Sei ´f:G \to G'´ Gruppenmorphismus. Dann ist ´N:=ker(f) \lhd G´.

Def. ´sgn(sigma) = (-1)^{\#\{(i,j) \;:\; i<j \text{ und } sigma(i) > sigma(j)\}}´

Lemma. ´\forall sigma \in S_n : sgn(sigma) = (Produkt) \frac{sigma(j) - sigma(i)}{j-i}´.

Def. ´sigma in S_n´ heißt gerade, gdw. ´sgn(sigma) = 1´. Ungerade, gdw. ´sgn(sigma) = -1´.

Def. ´ker(sgn) = A_n = \{ sigma in S_n : sgn(sigma) = 1 \}´ heißt die *alternierende Gruppe*.

Bmk. ´A_n \lhd S_n´. ´|A_n| = \frac{n!}{2}´.

Isomorphiesatz. Sei ´phi : G to G'´ Gruppenmorphismus. Dann ist ´ker(phi) \lhd G´ und es gibt einen
kanonischen Isomorphismus von Gruppen ´\overline φ : G/Ker(φ) gleichschlange to φ(G)´. (´φ(G) <= G'´
Untergruppe.)

Bmk. Falls ´φ´ surjektiv ist, d.h. ´φ(G) = G'´, dann bildet ´\overline φ´ nach ´G'´ ab.
